DIM/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('school.urls', 'school'), namespace='school')),
    path('auth/', include(('authentication.urls', 'authentication'), namespace='auth')),
    path('profiles/', include(('profiles.urls', 'profiles'), namespace='profiles')),
    path('basket/', include(('basket.urls', 'basket'), namespace='basket')),
    path('api/v1/', include(('api.urls', 'api'), namespace='api')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

from .views import registration, confirm_email
from .forms import PsswrdResetForm, PsswrdResetConfirmForm

urlpatterns = [

    path('registration/', registration, name='registration'),
    path('registration/confirm_email/<slug:uidb64>/<slug:token>', confirm_email, name='confirm_email'),

    path('login/', auth_views.LoginView.as_view(template_name='authentication/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('password_change/', auth_views.PasswordChangeView.as_view(
        template_name='authentication/password_change_form.html',
        success_url='/auth/password_change/done/',
    ), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='authentication/password_change_done.html',
    ), name='password_change_done'),

    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name='authentication/password_reset_form.html',
        success_url='/auth/password_reset/confirm/',
        email_template_name='authentication/password_reset_email.html',
        form_class=PsswrdResetForm
    ), name='password_reset'),

    path('password_reset/confirm/', TemplateView.as_view(
        template_name="authentication/reset_status.html"
    ), name='password_reset_done'),

    path('password_reset/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='authentication/password_reset_confirm.html',
        success_url='/auth/password_reset/complete/',
        form_class=PsswrdResetConfirmForm
    ), name='password_reset_confirm'),

    path('password_reset/complete/', TemplateView.as_view(
        template_name="authentication/reset_status.html"
    ), name='password_reset_complete'),
]

authentication/models.py
from django.contrib.auth.models import (AbstractBaseUser, BaseUserManager,
                                        PermissionsMixin)
from django.core.mail import send_mail
from django.db import models
from django.utils.translation import gettext_lazy as _


class CustomAccountManager(BaseUserManager):

    def create_superuser(self, email, username, password, **other_fields):

        other_fields.setdefault('is_staff', True)
        other_fields.setdefault('is_superuser', True)
        other_fields.setdefault('is_active', True)

        if other_fields.get('is_staff') is not True:
            raise ValueError(
                'Superuser must be assigned to is_staff=True.')
        if other_fields.get('is_superuser') is not True:
            raise ValueError(
                'Superuser must be assigned to is_superuser=True.')

        return self.create_user(email, username, password, **other_fields)

    def create_user(self, email, username, password, **other_fields):

        if not email:
            raise ValueError(_('You must provide an email address'))

        email = self.normalize_email(email)
        user = self.model(email=email, username=username,
                          **other_fields)
        user.set_password(password)
        user.save()
        return user


class MyUser(AbstractBaseUser, PermissionsMixin):

    email = models.EmailField(_('email address'), unique=True)
    username = models.CharField(max_length=150, unique=True)
    first_name = models.CharField(max_length=150, blank=True)
    last_name = models.CharField(max_length=150, blank=True)
    about = models.TextField(_('about'), max_length=500, blank=True)
    # Delivery details
    phone_number = models.CharField(max_length=15, blank=True)
    town_city = models.CharField(max_length=150, blank=True)
    # User Status
    is_teacher = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = CustomAccountManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    class Meta:
        verbose_name = "Користувач"
        verbose_name_plural = "Користувачі"

    def email_user(self, subject, message):
        send_mail(
            subject,
            message,
            'l@1.com',
            [self.email],
            fail_silently=False,
        )

    def __str__(self):
        return self.username

authentication/forms.py
from django import forms
from django.contrib.auth.forms import PasswordResetForm, SetPasswordForm, UserCreationForm

from authentication.models import MyUser


class RegistrationForm(UserCreationForm):
    username = forms.CharField(
        label='Enter Username', min_length=4, max_length=50, help_text='Required')
    email = forms.EmailField(max_length=100, help_text='Required', error_messages={
        'required': 'Sorry, you will need an email'})

    class Meta:
        model = MyUser
        fields = ('username', 'email', 'password1', 'password2', )

    def clean_username(self):
        username = self.cleaned_data['username'].lower()
        r = MyUser.objects.filter(username=username)
        if r.count():
            raise forms.ValidationError("Username already exists")
        return username

    def clean_email(self):
        email = self.cleaned_data['email']
        if MyUser.objects.filter(email=email).exists():
            raise forms.ValidationError(
                'Please use another Email, that is already taken')
        return email


class PsswrdResetForm(PasswordResetForm):

    email = forms.EmailField(max_length=254,
                             widget=forms.TextInput(
                                 attrs={'placeholder': 'email'}
                             ))

    def clean_email(self):
        email = self.cleaned_data.get('email')
        user = MyUser.objects.filter(email=email)
        if not user:
            raise forms.ValidationError(
                'No such email in the database'
            )
        return email


class PsswrdResetConfirmForm(SetPasswordForm):
    new_password1 = forms.CharField(
        label='New password', widget=forms.PasswordInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'New Password', 'id': 'form-newpass'}))
    new_password2 = forms.CharField(
        label='Repeat password', widget=forms.PasswordInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'New Password', 'id': 'form-new-pass2'}))

authentication/views.py
from django.contrib.auth import login
from django.contrib.sites.shortcuts import get_current_site
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode

from .forms import RegistrationForm
from .models import MyUser
from .token import account_activation_token


def registration(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect('/')
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        print(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            # EMAIL SETUP
            current_site = get_current_site(request)
            subject = 'Activate your Account'
            message = render_to_string('authentication/account_activation_email.html',
                                       {'user': user, 'domain': current_site,
                                        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                                        'token': account_activation_token.make_token(user),
                                        })
            user.email_user(subject=subject, message=message)
            # END EMAIL PART

            return render(request, 'authentication/registration_success.html')  #  HttpResponseRedirect('/')
        else:
            return HttpResponse(form.errors)
    else:
        form = RegistrationForm()
        return render(request, 'authentication/registration.html', {'form': form})


def confirm_email(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = MyUser.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, user.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        return redirect('profiles:dashboard')
    else:
        return HttpResponse('Activation invalid')

authentication/templates/authentication/account_activation_email.html
{% autoescape off %}

Hi {{ user.username }}

Your account has been created. Press the link below to activate

http://{{ domain }}{% url 'auth:confirm_email' uidb64=uid token=token %}

{% endautoescape %}

authentication/templates/authentication/delete_confirm.html
DELETE CONFIRMED

authentication/templates/authentication/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
<h1>LOGIN</h1>
<form class="form" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn">Логін</button>
</form>
<a href="{% url 'auth:registration' %}">Зареєструватися</a>
<a href="{% url 'auth:password_reset' %}">Забули пароль?</a>
</body>
</html>

authentication/templates/authentication/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

authentication/templates/authentication/password_change_done.html
{% extends "base.html" %}
{% block title %}Change password{% endblock %}
{% block content %}

<h1>Ваш пароль успішно змінено</h1>
<h3>Повернутися в <a href="{% url 'profiles:dashboard' %}">профіль</a></h3>

{% endblock %}

authentication/templates/authentication/password_change_form.html
{% extends "base.html" %}
{% block title %}Change password{% endblock %}
{% block content %}

<form class="account-form p-4 rounded col-lg-8 mx-auto" method="post" action="{% url 'auth:password_change' %}">
    <p class="h3 mb-4 font-weight-bold">Want to cahnge your password?</p>
    {% if form.errors %}
    <div class="alert alert-primary" role="alert">
        Error: Please try again!
    </div>
    {% endif %}
    {% csrf_token %}
    <label class="small font-weight-bold">{{ form.old_password.label }}</label>
    {{ form.old_password }}
    <label class="small font-weight-bold">{{ form.new_password1.label }}</label>
    {{ form.new_password1 }}
    <label class="small font-weight-bold">{{ form.new_password2.label }}</label>
    {{ form.new_password2 }}
    <button class="btn btn-primary btn-block py-2 mb-4 mt-5 fw-bold w-100" type="submit" value="Send e-mail">
        Змінити пароль
    </button>
    <p class="text-center"><a href="{% url 'profiles:dashboard' %}">Profile</a></p>
</form>

{% endblock %}

authentication/templates/authentication/password_reset_confirm.html
{% extends "base.html" %}
{% block title %}Log-in{% endblock %}
{% block content %}

{% if request.user.is_authenticated %}
<script>
    window.location.href = '{% url "account:dashboard" %}';
</script>
{% endif %}

<style>
    .login,
    .image {
        min-height: 100vh;
    }

    .bg-image {
        background-image: url('https://picsum.photos/id/433/1080');
        background-size: cover;
        background-position: center center;
    }

    .container-fluid {
        max-width: 100%;
    }

    body {
        margin-bottom: 0px;
    }

    .account-form input {
        border: 2px solid #ccc;
        height: calc(2em + .75rem + 2px);
    }

    .account-form input:focus {
        border-color: #1497ff;
        box-shadow: inset 0 0px 0px rgba(0, 0, 0, 0.075), 0 0 0px rgba(255, 0, 0, 0.6);
    }
</style>


<div class="container-fluid">
    <div class="row no-gutter">
        <div class="col-md-6 bg-light">
            <div class="login d-flex align-items-center py-5">
                <div class="container">
                    <div class="row">
                        <div class="col-12 col-md-12 mx-auto">

                            <form class="login-form p-4 rounded" method="post">
                                {% csrf_token %}
                                <h1 class="h4 mb-4 font-weight-bold">Change your password</h1>
                                <p>Use the form below to change your password.</p>

                                {% if form.errors %}
                                <div class="alert alert-primary" role="alert">
                                    Error: Please try again!
                                </div>
                                {% endif %}

                                <label class="small font-weight-bold">{{ form.new_password1.label}}</label>
                                {{ form.new_password1 }}
                                <label class="small font-weight-bold">{{ form.new_password2.label}}</label>
                                {{ form.new_password2 }}
                                <ul>
                                    <li>Your password can’t be too similar to your other personal information.</li>
                                    <li>Your password must contain at least 8 characters.</li>
                                    <li>Your password can’t be a commonly used password.</li>
                                    <li>Your password can’t be entirely numeric.</li>
                                </ul>
                                <button class="btn btn-primary btn-block py-2 mb-4 mt-5 font-weight-bold" type="submit"
                                    value="Change">Submit
                                </button>
                            </form>

                            <p class="small text-center pt-4">
                                <a href="{% url 'auth:login' %}">Already have an account?</a>
                            </p>
                            <p class="small text-center">
                                <a href="{% url 'auth:registration' %}">Help Center?</a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6 d-none d-md-flex bg-image"></div>
    </div>
</div>
{% endblock %}

authentication/templates/authentication/password_reset_email.html
{% load i18n %}
{% autoescape off %}
{% blocktranslate %}
You're receiving this email because you requested a password reset for your user account at {{ site_name }}.
{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'auth:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

authentication/templates/authentication/password_reset_form.html
{% extends "base.html" %}
{% block title %}Reset password{% endblock %}
{% block content %}

{% if request.user.is_authenticated %}
<script>
        window.location.href = '{% url "profiles:dashboard" %}';

</script>
{% endif %}

<form class="account-form p-4 rounded col-lg-8 mx-auto" method="post" action="{% url 'auth:password_reset' %}">
    <p class="h3 mb-4 font-weight-bold">Forgotten your password?</p>
    <p>Enter your e-mail address to obtain a new password.</p>
    {% if form.errors %}
    <div class="alert alert-primary" role="alert">
        Error: Please try again!
    </div>
    {% endif %}
    {% csrf_token %}
    <label class="small font-weight-bold">{{ form.email.label }}</label>
    {{ form.email }}
    <button class="btn btn-primary btn-block py-2 mb-4 mt-5 fw-bold w-100" type="submit" value="Send e-mail">Send
        e-mail
    </button>
    <p class="text-center"><a href="{% url 'auth:login' %}">Login</a></p>
</form>
{% endblock %}

authentication/templates/authentication/registration.html
{% extends 'base.html' %}

{% block title %}
Registration
{% endblock %}

{% block content %}

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-secondary">Send</button>
</form>

{% endblock %}

authentication/templates/authentication/registration_success.html
{% extends 'base.html' %}

{% block title %}
Registration success
{% endblock %}

{% block content %}
<h1>Registration success. Email was sent!!!</h1>
{% endblock %}

authentication/templates/authentication/reset_status.html
{% extends "base.html" %}
{% block title %}Log-in{% endblock %}
{% block content %}

<style>
    .container-fluid {
        max-width: 100%;
    }

    .account-form input {
        border: 2px solid #ccc;
        height: calc(2em + .75rem + 2px);
    }

    .account-form input:focus {
        border-color: #1497ff;
        box-shadow: none;
    }
</style>


<div class="container-fluid">
    <div class="row no-gutter">
        <div class="col-md-12">
            <div class="login d-flex align-items-center py-5">
                <div class="container">
                    <div class="row">
                        <div class="col-12 col-lg-6  mx-auto">
                            <div class="p-4">
                                {% if 'confirm' in request.get_full_path %}
                                        <h3 class="mb-4">Password Reset Confirm</h3>
                                        <p>Check your email for instructions</p>
                                {% endif%}
                                {% if 'complete' in request.get_full_path %}
                                        <h3 class="mb-4">Password Reset Success</h3>
                                        <a href="{% url 'auth:login' %}">Login</a>
                                {% endif%}
                            </div>       
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}