DIM/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('school.urls', 'school'), namespace='school')),
    path('auth/', include(('authentication.urls', 'authentication'), namespace='auth')),
    path('profiles/', include(('profiles.urls', 'profiles'), namespace='profiles')),
    path('basket/', include(('basket.urls', 'basket'), namespace='basket')),
    path('api/v1/', include(('api.urls', 'api'), namespace='api')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

basket/urls.py
from django.urls import path
from .views import basket_summary, basket_add, basket_delete, basket_update

urlpatterns = [
    path('', basket_summary, name='basket'),
    path('add/', basket_add, name='basket_add'),
    path('delete/', basket_delete, name='basket_delete'),
    path('update/', basket_update, name='basket_update'),
]

basket/models.py
from django.db import models

basket/views.py
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required

from school.models import Abonement
from .basket import Basket


@login_required()
def basket_summary(request):
    return render(request, 'basket/basket_summary.html')


def basket_add(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        product = get_object_or_404(Abonement, id=product_id)
        basket.add(product=product, quantity=product_qty)

        basket_qty = len(basket)
        response = JsonResponse({'quantity': basket_qty})
        return response


def basket_delete(request):
    basket = Basket(request)
    if request.POST.get('action') == 'delete':
        product_id = request.POST.get('productid')
        print(len(basket))
        basket.delete(product_id=product_id)
        basket_total = basket.get_total_price()
        basket_quantity = len(basket)
        response = JsonResponse({'quantity': basket_quantity,
                                 'total': basket_total})
        return response


def basket_update(request):
    basket = Basket(request)
    if request.POST.get('action') == 'update':
        product_id = request.POST.get('productid')
        product_qty = int(request.POST.get('productqty'))

        basket.update(product_id=product_id, quantity=product_qty)

        basket_quantity = len(basket)
        basket_total = basket.get_total_price()
        response = JsonResponse({'quantity': basket_quantity,
                                 'total': basket_total})
        return response

basket/templates/basket/basket_summary.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>Корзина</title>
{% endblock %}


{% block content %}

<main>
    <div class="container">
        <h1 class="h5">BASKET PAGE</h1>
        {% for item in basket %}
        {% with abonement=item.abonement %}
        <div data-index="{{abonement.id}}" class="row mb-4 border product-item">
            <div class="col-md-3 col-lg-2 order-md-first bg-light">
                <img class="img-fluid mx-auto d-block" width="120px" alt="Responsive image"
                     src="{{ abonement.photo }}">
            </div>
            <div class="col-md-9 col-lg-10 ps-md-3 ps-lg-10">
                <a href="{{ abonement.get_absolute_url }}" class="text-decoration-none text-reset">
                    <h1 class="h5 pt-2">{{ abonement }}</h1>
                </a>
                <div class="border">
                    <div class="col border-bottom">
                        <div class="row p-3">
                            <div class="col-6">Ціна</div>
                            <div class="col-6 text-end"><span class="h6 fw-bold">{{ abonement.price }} UAH</span></div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="row p-3">
                            <div class="col-12">
                                <label for="select{{abonement.id}}">Кількість</label>
                                <select id="select{{abonement.id}}">
                                    <option selected>
                                        {{item.quantity}}
                                    </option>
                                    <option value="">1</option>
                                    <option value="">2</option>
                                    <option value="">3</option>
                                    <option value="">4</option>
                                </select>
                                <button type="button" id="update-button" data-index="{{abonement.id}}"
                                        class="btn btn-outline-secondary btn-sm update-button">
                                    Update
                                </button>
                                <button type="button" id="delete-button" data-index="{{abonement.id}}"
                                        class="btn btn-outline-secondary btn-sm delete-button">
                                    Delete
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        {% endwith %}
        {% endfor %}
        <div class="col-12 text-end">
            <div class="h6 fw-hold">Сума: <span id="subtotal">{{ basket.get_total_price }}</span> UAH</div>

        </div>

    </div>
</main>

<script>
    $(document).on('click', '.delete-button', function (e) {
        e.preventDefault();
        let prodid = $(this).data('index');
        $.ajax({
            type: 'POST',
            url: "{% url 'basket:basket_delete' %}",
            data: {
                productid: $(this).data('index'),
                csrfmiddlewaretoken: "{{ csrf_token }}",
                action: 'delete',
            },
            success: function (json) {
                $('.product-item[data-index="'+ prodid +'"]').remove();
                document.getElementById("basket-qty").innerHTML = json.quantity;
                document.getElementById("subtotal").innerHTML = json.total;
            },
            error: function (xhr, errmsg, err) {},
        });
    });

    // Update
    $(document).on('click', '.update-button', function (e) {
        e.preventDefault();
        let prodid = $(this).data('index');
        $.ajax({
            type: 'POST',
            url: "{% url 'basket:basket_update' %}",
            data: {
                productid: $(this).data('index'),
                productqty: $('#select' + prodid + ' option:selected').text(),
                csrfmiddlewaretoken: "{{ csrf_token }}",
                action: 'update',
            },
            success: function (json) {
                document.getElementById("basket-qty").innerHTML = json.quantity;
                document.getElementById("subtotal").innerHTML = json.total;
            },
            error: function (xhr, errmsg, err) {},
        });
    })

</script>
{% endblock %}