DIM/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('school.urls', 'school'), namespace='school')),
    path('auth/', include(('authentication.urls', 'authentication'), namespace='auth')),
    path('profiles/', include(('profiles.urls', 'profiles'), namespace='profiles')),
    path('basket/', include(('basket.urls', 'basket'), namespace='basket')),
    path('api/v1/', include(('api.urls', 'api'), namespace='api')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.urls import path
from .views import TeacherList, TeacherDetail

urlpatterns = [
    path('teachers/', TeacherList.as_view(), name='teachers_list'),
    path('teachers/<int:pk>/', TeacherDetail.as_view(), name='teacher_detail'),
]

authentication/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

from .views import registration, confirm_email
from .forms import PsswrdResetForm, PsswrdResetConfirmForm

urlpatterns = [

    path('registration/', registration, name='registration'),
    path('registration/confirm_email/<slug:uidb64>/<slug:token>', confirm_email, name='confirm_email'),

    path('login/', auth_views.LoginView.as_view(template_name='authentication/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('password_change/', auth_views.PasswordChangeView.as_view(
        template_name='authentication/password_change_form.html',
        success_url='/auth/password_change/done/',
    ), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='authentication/password_change_done.html',
    ), name='password_change_done'),

    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name='authentication/password_reset_form.html',
        success_url='/auth/password_reset/confirm/',
        email_template_name='authentication/password_reset_email.html',
        form_class=PsswrdResetForm
    ), name='password_reset'),

    path('password_reset/confirm/', TemplateView.as_view(
        template_name="authentication/reset_status.html"
    ), name='password_reset_done'),

    path('password_reset/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='authentication/password_reset_confirm.html',
        success_url='/auth/password_reset/complete/',
        form_class=PsswrdResetConfirmForm
    ), name='password_reset_confirm'),

    path('password_reset/complete/', TemplateView.as_view(
        template_name="authentication/reset_status.html"
    ), name='password_reset_complete'),
]

basket/urls.py
from django.urls import path
from .views import basket_summary, basket_add, basket_delete, basket_update

urlpatterns = [
    path('', basket_summary, name='basket'),
    path('add/', basket_add, name='basket_add'),
    path('delete/', basket_delete, name='basket_delete'),
    path('update/', basket_update, name='basket_update'),
]

school/urls.py
from django.urls import path
from .views import home, StylesList, StyleDetail, TeachersList, TeacherDetail, GroupList, \
    AbonementsList, Schedule, AbonementsDetail

urlpatterns = [
    path('', home, name='home'),
    path('styles', StylesList.as_view(), name='styles_list'),
    path('styles/<slug:slug>', StyleDetail.as_view(), name='style_detail'),
    path('teachers', TeachersList.as_view(), name='teachers_list'),
    path('teachers/<slug:slug>', TeacherDetail.as_view(), name='teacher_detail'),
    path('groups', GroupList.as_view(), name='groups_list'),
    path('abonements', AbonementsList.as_view(), name='abonements_list'),
    path('abonements/<int:pk>', AbonementsDetail.as_view(), name='abonement_detail'),
    path('schedule/<str:day>', Schedule.as_view(), name='schedule'),
    path('schedule', Schedule.as_view(), name='schedule'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}{% endblock %}
    </title>


    {% block styles %}
    <style>
        a:link {
            text-decoration: none;
        }
    </style>
    {% endblock %}
    <script
            src="https://code.jquery.com/jquery-3.6.3.min.js"
            integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU="
            crossorigin="anonymous">
    </script>
</head>

<body>
{% block navbar %}{% include 'navbar.html' %}{% endblock %}
{% block content %}{% endblock %}
</body>
</html>

templates/navbar.html
{% load bootstrap5 %}

{% bootstrap_css %}
{% bootstrap_javascript %}

<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'school:home' %}">ДІМ</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'school:styles_list' %}">Стилі</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'school:teachers_list' %}">Педагоги</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'school:groups_list' %}">Групи</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'school:abonements_list' %}">Абонементи</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'school:schedule' %}">Розклад</a>
                </li>
            </ul>
                <div class="d-flex gap-1">

                    {% if user.is_authenticated %}
                      <div id="basket">
                          {% with total_qty=basket|length %}
                          <span id="basket-qty" class="badge bg-secondary">
                            {% if total_qty > 0 %}
                              {{ total_qty }}
                            {% else %}
                              0
                            {% endif %}
                          </span>
                          {% endwith %}
                          <a href="{% url 'basket:basket' %}" class="btn btn-secondary">Корзина</a>
                    </div>
                      <a href="{% url 'profiles:dashboard' %}" class="btn btn-secondary">Профіль</a>
                      <a href="{% url 'auth:logout' %}" class="btn btn-secondary">Вийти</a>
                    {% else %}
                      <a href="{% url 'auth:login' %}" class="btn btn-secondary">Увійти</a>
                    {% endif %}

                </div>


            </form>
        </div>
    </div>
</nav>