DIM/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('school.urls', 'school'), namespace='school')),
    path('auth/', include(('authentication.urls', 'authentication'), namespace='auth')),
    path('profiles/', include(('profiles.urls', 'profiles'), namespace='profiles')),
    path('basket/', include(('basket.urls', 'basket'), namespace='basket')),
    path('api/v1/', include(('api.urls', 'api'), namespace='api')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

basket/urls.py
from django.urls import path
from .views import basket_summary, basket_add, basket_delete, basket_update

urlpatterns = [
    path('', basket_summary, name='basket'),
    path('add/', basket_add, name='basket_add'),
    path('delete/', basket_delete, name='basket_delete'),
    path('update/', basket_update, name='basket_update'),
]

school/urls.py
from django.urls import path
from .views import home, StylesList, StyleDetail, TeachersList, TeacherDetail, GroupList, \
    AbonementsList, Schedule, AbonementsDetail

urlpatterns = [
    path('', home, name='home'),
    path('styles', StylesList.as_view(), name='styles_list'),
    path('styles/<slug:slug>', StyleDetail.as_view(), name='style_detail'),
    path('teachers', TeachersList.as_view(), name='teachers_list'),
    path('teachers/<slug:slug>', TeacherDetail.as_view(), name='teacher_detail'),
    path('groups', GroupList.as_view(), name='groups_list'),
    path('abonements', AbonementsList.as_view(), name='abonements_list'),
    path('abonements/<int:pk>', AbonementsDetail.as_view(), name='abonement_detail'),
    path('schedule/<str:day>', Schedule.as_view(), name='schedule'),
    path('schedule', Schedule.as_view(), name='schedule'),
]

school/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


class Category(models.Model):
    name = models.CharField('назва', max_length=32, unique=True)
    salary = models.DecimalField('ставка', max_digits=5, decimal_places=2)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категорія'
        verbose_name_plural = 'Категорії'
        ordering = ['-salary']


class Style(models.Model):
    name = models.CharField('стиль', max_length=64)
    description = models.TextField('опис', blank=True, null=True)
    photo = models.ImageField(upload_to='styles/', blank=True, null=True)
    slug = models.SlugField('слаг', max_length=32, blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('school:style_detail', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        return super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Стиль'
        verbose_name_plural = 'Стилі'
        ordering = ['name']


class Teacher(models.Model):
    # first_name = models.CharField('ім’я', max_length=64)
    # last_name = models.CharField('прізвище', max_length=64)
    # middle_name = models.CharField('по-батькові', max_length=64, blank=True, null=True)
    nickname = models.CharField('псевдонім', max_length=64)
    photo = models.ImageField(upload_to='teachers/', blank=True, verbose_name='фото')
    slug = models.SlugField(max_length=50, blank=True, verbose_name='слаг')
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, verbose_name='категорія')
    styles = models.ManyToManyField(
        Style,
        verbose_name='стилі',
        related_name='teachers',
        related_query_name='teacher'
    )
    user = models.OneToOneField('authentication.MyUser', null=True, blank=True, on_delete=models.SET_NULL)

    # def save(self, *args, **kwargs):
    #     if not self.nickname:
    #         self.nickname = f'{self.first_name} {self.last_name}'
    #     if not self.slug:
    #         self.slug = slugify(f'{self.first_name} {self.last_name}')
    #     return super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('school:teacher_detail', kwargs={'slug': self.slug})

    def __str__(self):
        return self.nickname

    class Meta:
        verbose_name = 'Педагог'
        verbose_name_plural = 'Педагоги'
        ordering = ['nickname']


class Hall(models.Model):
    number = models.PositiveSmallIntegerField('номер')
    square = models.DecimalField('площа', max_digits=5, decimal_places=2)
    rent_price = models.DecimalField('ціна оренди', max_digits=6, decimal_places=2)
    rent_for_teachers = models.DecimalField('оренда для педагогів', max_digits=6, decimal_places=2)

    def __str__(self):
        return f'Зал-{self.number}'

    class Meta:
        verbose_name = 'Зал'
        verbose_name_plural = 'Зали'
        ordering = ['number']


class Group(models.Model):
    LEVEL_CHOICES = [
        (0, 'all levels'),
        (1, 'beginner'),
        (2, 'middle'),
        (3, 'advanced'),
    ]

    DAYS_CHOICES = [
        (1, 'Mon'),
        (2, 'Tue'),
        (3, 'Wed'),
        (4, 'Thu'),
        (5, 'Fri'),
        (6, 'Sat'),
        (7, 'Sun'),
    ]

    teacher = models.ForeignKey('Teacher', on_delete=models.CASCADE, related_name='groups', verbose_name='педагог')
    style = models.ForeignKey('Style', on_delete=models.CASCADE, related_name='groups', verbose_name='стиль')
    level = models.IntegerField('рівень', default=0, blank=True, choices=LEVEL_CHOICES)
    day_1 = models.IntegerField('день 1', choices=DAYS_CHOICES, blank=True)
    day_2 = models.IntegerField('день 2', choices=DAYS_CHOICES, blank=True)
    scheduled_time = models.TimeField('час')
    duration = models.IntegerField('тривалість')
    hall = models.ForeignKey(Hall, null=True, blank=True, on_delete=models.SET_NULL,
                             related_name='groups', verbose_name='зал')
    is_active = models.BooleanField('працює зараз', default=False, blank=True)

    @property
    def get_days(self):
        return f'{self.get_day_1_display()}-{self.get_day_2_display()}'

    def __str__(self):
        return f'{self.style} with {self.teacher} every {self.get_days} at {self.scheduled_time}'  # TODO format the time

    class Meta:
        verbose_name = 'Група'
        verbose_name_plural = 'Групи'
        ordering = ['day_1', 'scheduled_time']


class Abonement(models.Model):
    category = models.ForeignKey(
        Category,
        verbose_name='категорія',
        on_delete=models.CASCADE,
        related_name='abonement',
        null=True,
        blank=True,
    )
    number_of_lessons = models.PositiveSmallIntegerField('кількість занять')
    price = models.DecimalField('ціна', max_digits=6, decimal_places=2)
    duration = models.PositiveSmallIntegerField('тривалість')
    photo = models.ImageField('фото', blank=True, null=True)

    def __str__(self):
        if not self.category:
            return 'Unlimited'
        return f'{self.category}-{self.number_of_lessons}'

    def get_absolute_url(self):
        return reverse('school:abonement_detail', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = 'Абонемент'
        verbose_name_plural = 'Абонементи'
        ordering = ['price']


class AbonementItem(models.Model):
    abonement_type = models.ForeignKey('Abonement', related_name='items', on_delete=models.CASCADE)
    owner = models.ForeignKey('authentication.MyUser', related_name='abonements', on_delete=models.CASCADE)
    is_active = models.BooleanField('активний', default=False)
    activated_date = models.DateField('Дата активації', null=True, blank=True)
    lessons_used = models.PositiveSmallIntegerField('Використано занять', default=0)

    def __str__(self):
        return f'{self.abonement_type} - {self.owner}'

    class Meta:
        verbose_name = 'Придбаний абонемент'
        verbose_name_plural = 'Придбані абонементи'
        ordering = ['-activated_date']


class Lesson(models.Model):
    group = models.ForeignKey('Group', on_delete=models.CASCADE, related_name='lessons')
    students = models.ManyToManyField('AbonementItem', related_name='lessons')

    date = models.DateField('Дата')

    def save(self, *args, **kwargs):
        return super().save(*args, **kwargs)

school/views.py
from django.shortcuts import render
from django.views.generic import DetailView, ListView
from django.db.models import Q

from .models import Teacher, Style, Group, Abonement


def home(request):
    return render(request, 'school/home.html', context={'test': 'DIM'})


class StylesList(ListView):
    queryset = Style.objects.filter(teacher__isnull=False).prefetch_related('teachers').distinct()
    context_object_name = 'styles'
    template_name = 'school/styles_list.html'


class StyleDetail(DetailView):
    queryset = Style.objects.prefetch_related('teachers').all()
    context_object_name = 'style'
    template_name = 'school/style_detail.html'


class TeachersList(ListView):
    queryset = Teacher.objects.prefetch_related('styles').select_related('category').all()
    context_object_name = 'teachers'
    template_name = 'school/teacher_list.html'


class TeacherDetail(DetailView):
    queryset = Teacher.objects.prefetch_related('styles').select_related('category').all()


class GroupList(ListView):
    queryset = Group.objects.select_related('style', 'teacher', 'teacher__category').all()
    context_object_name = 'groups'
    template_name = 'school/groups_list.html'


class AbonementsList(ListView):
    queryset = Abonement.objects.select_related('category').all()
    context_object_name = 'abonements'
    template_name = 'school/abonements_list.html'


class AbonementsDetail(DetailView):
    queryset = Abonement.objects.select_related('category').all()
    context_object_name = 'abonement'
    template_name = 'school/abonement_detail.html'


class Schedule(ListView):
    context_object_name = 'groups'
    template_name = 'school/schedule.html'

    def get_queryset(self):
        if 'day' not in self.kwargs.keys():
            return Group.objects.select_related('teacher', 'hall', 'style', 'teacher__category') \
                .filter(is_active=True).order_by('day_1', 'scheduled_time')

        days = {'monday': 1, 'tuesday': 2, 'wednesday': 3, 'thursday': 4, 'friday': 5, 'saturday': 6, 'sunday': 7}
        day = days[self.kwargs['day']]
        return Group.objects.select_related('teacher', 'hall', 'style', 'teacher__category') \
            .filter(is_active=True).filter(Q(day_1=day) | Q(day_2=day)).order_by('day_1', 'scheduled_time') \
            .order_by('day_1', 'day_2', 'scheduled_time')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['days'] = {'monday': 'Понеділок', 'tuesday': 'Вівторок', 'wednesday': 'Середа', 'thursday': 'Четвер',
                           'friday': 'П’ятниця', 'saturday': 'Субота', 'sunday': 'Неділя'}
        return context

school/templates/school/abonement_detail.html
{% extends 'base.html' %}

{% block title %}Абонемент - {{ abonement }}{% endblock %}


{% block content %}
<h1>{{ abonement }}</h1>
<p>{{ abonement.price }}</p>

{% if abonement.photo %}
<img src="/media/{{object.photo}}" width="200">
{% endif %}
<div class="p-5">
    <label for="select">Кількість</label>
    <select id="select">
        <option value="1">1</option>
        <option value="2">2</option>
        <option value="3">3</option>
        <option value="4">4</option>
    </select>
    <button type="button" id="add-button" value="{{ abonement.id }}">Додати в корзину</button>
</div>



<script>
    $(document).on('click', '#add-button', function (e) {
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: "{% url 'basket:basket_add' %}",
            data: {
                productid: $('#add-button').val(),
                productqty: $('#select option:selected').text(),
                csrfmiddlewaretoken: "{{ csrf_token }}",
                action: 'post',
            },
            success: function (json) {
                document.getElementById("basket-qty").innerHTML = json.quantity;
            },
            error: function (xhr, errmsg, err) {
                console.log('error')
            },
        });
    })

</script>
{% endblock %}

school/templates/school/abonements_list.html
{% extends 'base.html' %}

{% block title %}
Абонементи
{% endblock %}

{% block content %}
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 g-4 mx-2">
    {% for abonement in abonements %}
    <div class="col">
        <div class="card h-100">
            {% if abonement.photo %}
            <img src="{{ abonement.photo }}" class="card-img-top" alt="{{ abonement }}-photo">
            {% else %}
            <img src="..." class="card-img-top" alt="NO PHOTO">
            {% endif %}
            <div class="card-body">
                <h5 class="card-title"><a href="{% url 'school:abonement_detail' abonement.pk %}">{{ abonement }}</a></h5>
                <p class="card-text">{{ abonement.price }} грн</p>
            </div>
            <div class="card-footer d-flex justify-content-evenly">
                <span class="badge bg-secondary">{{ abonement.duration }} днів</span>

            </div>
        </div>
    </div>
    {% endfor %}

</div>

{% endblock %}

school/templates/school/groups_list.html
{% extends 'base.html' %}

{% block title %}
Групи
{% endblock %}

{% block content %}

<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 g-4 mx-2">
    {% for group in groups %}
    <div class="col">
        <div class="card h-100">
            <div class="card-body">
                <div class="d-flex justify-content-between">
                    <h5 class="card-title">
                        <a href="{% url 'school:teacher_detail' group.teacher.slug %}">{{ group.teacher }}</a>
                    </h5>
                    <h5>
                        <a href="{% url 'school:style_detail' group.style.slug %}">{{ group.style }}</a>
                    </h5>
                    <span class="badge bg-secondary" style="color: black;">{{ group.teacher.category }}</span>
                </div>
                <ul>
                    <li>{{ group.get_level_display }}</li>
                    <li>{{ group.get_days }}</li>
                    <li>{{ group.scheduled_time }}</li>
                    <li>{{ group.duration }} min</li>
                </ul>
            </div>
            <div class="card-footer d-flex justify-content-evenly">
                <small>Some footer here</small>
            </div>
        </div>
    </div>
    {% endfor %}

</div>

{% endblock %}

school/templates/school/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
DIM
{% endblock %}


{% block content %}
    <h1>{{ test }}</h1>
{% endblock %}

school/templates/school/schedule.html
{% extends 'base.html' %}

{% block title %}
Розклад
{% endblock %}

{% block content %}
<div class="d-flex justify-content-center">
    {% for day_en, day_ua in days.items %}
    <a class="btn btn-sm btn-secondary mx-2" href="{% url 'school:schedule' day_en %}">{{day_ua}}</a>
    {% endfor %}
    <a class="btn btn-sm btn-secondary mx-2" href="{% url 'school:schedule' %}">Усі</a>
</div>

<div class="container-fluid">
    <table class="table table-stripped my-2">
        <thead>
        <tr>
            <th>Час</th>
            <th>Педагог</th>
            <th>Стиль</th>
            <th>Дні</th>
            <th>Рівень</th>
            <th>Категорія</th>
        </tr>
        </thead>
        <tbody>
        {% for group in groups%}
        <tr>
            <td>{{ group.scheduled_time }}</td>
            <td>{{ group.teacher }}</td>
            <td>{{ group.style }}</td>
            <td>{{ group.get_days }}</td>
            <td>{{ group.get_level_display }}</td>
            <td>{{ group.teacher.category }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

school/templates/school/style_detail.html
{% extends 'base.html' %}

{% block title %}
{{ style.name }}
{% endblock %}

{% block content %}
<div class="container-fluid px-5">
    <h1>{{ style.name }}</h1>
<p>{{ style.description }}</p>
<h4>Педагоги:</h4>
{% for teacher in style.teachers.all %}
<a href="{% url 'school:teacher_detail' teacher.slug %}">{{ teacher.nickname }}</a><br>
{% endfor %}
{% if style.photo %}
<img src="/media/{{ style.photo }}" width="200">
{% endif %}
</div>

{% endblock %}

school/templates/school/styles_list.html
{% extends 'base.html' %}

{% block title %}
Стилі
{% endblock %}

{% block content %}
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 g-4 mx-2">
    {% for style in styles %}
    <div class="col">
        <div class="card h-100">
            {% if style.photo %}
            <img src="{{ style.photo }}" class="card-img-top" alt="{{ style.name }}-photo">
            {% else %}
            <img src="..." class="card-img-top" alt="NO PHOTO">
            {% endif %}
            <div class="card-body">
                <h5 class="card-title"><a href="{% url 'school:style_detail' style.slug %}">{{ style.name }}</a></h5>
                <p class="card-text">{{ style.description }}</p>
            </div>
            <div class="card-footer d-flex justify-content-evenly">
                {% for teacher in style.teachers.all|slice:":2" %}
                <span class="badge"><a href="{% url 'school:teacher_detail' teacher.slug %}">{{ teacher }}</a></span>
                {% endfor %}
            </div>
        </div>
    </div>
    {% endfor %}

</div>

{% endblock %}

school/templates/school/teacher_detail.html
{% extends 'base.html' %}

{% block title %}
{{ object.nickname }}
{% endblock %}


{% block content %}
<h1>{{ object.nickname }}</h1>
<p>{{ object.category }}</p>
<ul>
{% for style in object.styles.all %}
    <li><a href="{% url 'school:style_detail' style.slug %}">{{ style }}</a></li>
{% endfor %}
</ul>
{% if object.photo %}
<img src="/media/{{object.photo}}" width="200">
{% endif %}
{% endblock %}

school/templates/school/teacher_list.html
{% extends 'base.html' %}

{% block title %}
Педагоги
{% endblock %}

{% block content %}
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 g-4 mx-2">
    {% for teacher in teachers %}
    <div class="col">
        <div class="card h-100">
            {% if teacher.photo %}
            <img src="{{ style.photo }}" class="card-img-top" alt="{{ style.name }}-photo">
            {% else %}
            <img src="..." class="card-img-top" alt="NO PHOTO">
            {% endif %}
            <div class="card-body d-flex justify-content-between">
                <h5 class="card-title"><a href="{% url 'school:teacher_detail' teacher.slug %}">{{ teacher.nickname }}</a>

                </h5>
                <span class="badge bg-secondary" style="color: black;">{{ teacher.category }}</span>
            </div>
            <div class="card-footer d-flex justify-content-evenly">
                {% for style in teacher.styles.all %}
                <span class="badge"><a href="{% url 'school:style_detail' style.slug %}">{{ style }}</a></span>
                {% endfor %}
            </div>
        </div>
    </div>
    {% endfor %}

</div>
{% endblock %}